// Generates src/ort-version.ts and copies the onnxruntime-web .wasm/.mjs assets
// out of the resolved node_modules install into ./ort, next to main.js.
//
// Run BEFORE tsc/eslint/esbuild so the generated import exists on a clean
// checkout (build/lint/dev all depend on src/ort-version.ts, which is gitignored
// because it is a build artifact pinned to the installed dependency version).
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { createRequire } from "module";
import { fileURLToPath } from "url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));

// Resolve the onnxruntime-web package ROOT. Its package.json "exports" map blocks
// require.resolve("onnxruntime-web/package.json"), so resolve a file that IS
// exported (the wasm entry) and walk up to the dir that holds package.json.
// Falls back to the conventional node_modules location if resolution moves.
function resolveOrtDir() {
  try {
    let dir = dirname(require.resolve("onnxruntime-web"));
    for (let i = 0; i < 6; i++) {
      if (existsSync(join(dir, "package.json")) && existsSync(join(dir, "dist"))) {
        return dir;
      }
      dir = dirname(dir);
    }
  } catch {
    // fall through to the conventional path
  }
  const fallback = join(here, "node_modules", "onnxruntime-web");
  if (existsSync(join(fallback, "package.json"))) return fallback;
  throw new Error("Could not locate the onnxruntime-web package directory.");
}

const ortDir = resolveOrtDir();
// This version tracks the onnxruntime-web that @huggingface/transformers actually
// bundles — which is frequently a -dev snapshot (e.g. 1.22.0-dev.2025...). Do NOT
// pin it to a stable release independently: the self-hosted app:// primary .wasm
// and the JS glue transformers bundled must be the exact same build or ORT init
// fails ("create of undefined" / wasm-glue mismatch). The CDN fallback URL below
// is derived from this same version, so it can't drift either.
const ortVersion = JSON.parse(
  readFileSync(join(ortDir, "package.json"), "utf8"),
).version;

// The JSEP build is what transformers v3 uses for BOTH the WebGPU and WASM
// backends. Ship the wasm-only glue too so a non-jsep path still resolves.
const ORT_WASM_FILES = [
  "ort-wasm-simd-threaded.jsep.wasm",
  "ort-wasm-simd-threaded.jsep.mjs",
  "ort-wasm-simd-threaded.wasm",
  "ort-wasm-simd-threaded.mjs",
];

// onnxruntime-web's Emscripten glue decides node-vs-web with
//   n = typeof process=="object" && ... && "renderer" != process.type
// and, when n is true, does `await import("module")` + `require("worker_threads")`
// — Node-only modules that don't resolve in Obsidian's renderer ("Failed to
// resolve module specifier 'worker_threads'" / "no available backend found").
// process.type is read-only in Electron so we can't flip it. Instead we ship a
// PATCHED copy of the glue with that one check forced off (n is always false), so
// the glue takes the pure-web path (fetch the wasm, instantiate, run on the main
// thread). The plugin serves this patched glue to ort via wasmPaths.mjs.
function patchGlueForWeb(ortDir) {
  const src = readFileSync(
    join(ortDir, "dist", "ort-wasm-simd-threaded.jsep.mjs"),
    "utf8",
  );
  const needle = '"renderer"!=process.type';
  if (!src.includes(needle)) {
    throw new Error(
      "gen-ort: could not find the process.type node-check in the ort glue. The " +
        "onnxruntime-web build changed; update the patch in gen-ort.mjs.",
    );
  }
  // `... && "renderer"!=process.type` -> `... && !1` makes ENVIRONMENT_IS_NODE
  // false, so the worker_threads / node-fs branches are never taken.
  return src.split(needle).join("!1");
}

export function genOrt() {
  // 1) Write the pinned version + CDN-fallback URL + the web-patched glue source.
  const cdn = `https://cdn.jsdelivr.net/npm/onnxruntime-web@${ortVersion}/dist/`;
  const patchedGlue = patchGlueForWeb(ortDir);
  const contents =
    "// AUTO-GENERATED by gen-ort.mjs — do not edit by hand.\n" +
    "// Pinned to the onnxruntime-web version @huggingface/transformers actually\n" +
    "// bundles, so the runtime CDN fallback can never drift from the shipped glue.\n" +
    `export const ORT_WEB_VERSION = ${JSON.stringify(ortVersion)};\n` +
    `export const ORT_WEB_CDN = ${JSON.stringify(cdn)};\n` +
    "// The jsep wasm glue, patched so its Node check is always false (see\n" +
    "// patchGlueForWeb). Served to onnxruntime-web via a Blob URL at runtime so the\n" +
    "// glue takes the web path and never imports the Node-only 'worker_threads'.\n" +
    `export const ORT_GLUE_JSEP = ${JSON.stringify(patchedGlue)};\n`;
  const target = join(here, "src", "ort-version.ts");
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    current = "";
  }
  if (current !== contents) writeFileSync(target, contents);

  // 2) Copy the matching wasm assets next to main.js.
  const outDir = join(here, "ort");
  mkdirSync(outDir, { recursive: true });
  for (const f of ORT_WASM_FILES) {
    copyFileSync(join(ortDir, "dist", f), join(outDir, f));
  }

  return { ortVersion, cdn };
}

// Allow running directly: `node gen-ort.mjs`.
if (import.meta.url === `file://${process.argv[1]}`) {
  const { ortVersion: v } = genOrt();
  console.log(`Generated ort-version.ts and copied onnxruntime-web@${v} -> ort/`);
}
